package com.juanbai.examplespringbootprovider;

import com.juanbai.juanrpcspingbootstarter.annotation.EnableRpc;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication(scanBasePackages = {"com.juanbai.examplespringbootprovider"})
@EnableRpc
public class ExampleSpringbootProviderApplication {
    public static void main(String[] args) {
        SpringApplication. run(ExampleSpringbootProviderApplication.class, args);
    }
}
